### ISSUE TITLE
Not working on Alcatel Pixi 4 (7) OT-8063 WiFi

### ISSUE THREAD

**Issue by milankragujevic** [mt8127/android_device_alcatel_ttab#1]
This doesn't appear to work on Alcatel Pixi 4 (7) OT-8063 WiFi with the same CPU (Mediatek MT8127). Any clues why? It just reboots back into normal OS when I do adb reboot recovery. Flashed using SP Flash Tool and PIXI 4 scatter file.

**Comment by huckleberrypie** [comment]
Do you still have the original recovery with you? I might try porting this to your device if I have some spare time.

This one is actually for the Alcatel-made T-Mobile Telekom Puls.

**Comment by milankragujevic** [comment]
Hi, I have the original recovery, it's attached to this comment. The PIXI 4 (7) is a very similar device so it might be possible to port it, I'd really appreciate it.


[recovery.zip](https://github.com/mt8127/android_device_alcatel_ttab/files/2153029/recovery.zip)

**Comment by milankragujevic** [comment]
Sorry, why was this closed without comment?

**Comment by Stricted** [comment]
didnt you got my mail reply?

**Comment by Stricted** [comment]
this is what i wrote to you after i got your mail:

Hello Milan,

unfortunately i dont work on devices that i dont own, its a pain to
debug problems without having the devie infrom of me and sometimes it is
even impossible

you an use the source at https://github.com/mt8127 as reference for your
device
maybe you can even use it as it is and just swap the kernel

Regards,
Jan Altensen

i just saw the issue you opened
(https://github.com/mt8127/android_device_alcatel_ttab/issues/1)
this is my answer to it:

you need a device specific twrp recovery
with that you will be able to flash custom roms
you might need to build a device specific kernel based on the oem
released kernel

**Comment by huckleberrypie** [comment]
I could help with porting, but as Stricted said testing the recovery can be a bit more troublesome as we don't have physical access to the device.
